### ISSUE TITLE
landuse - diversity

### ISSUE THREAD

**Issue by temospena** [U-Shift/SiteSelection#7]
Regarding land use, it may be hard to filter what we really want. Most buildings only have tag building: yes`, without any type.
![image](https://github.com/U-Shift/SiteSelection/assets/39107166/113f4c8b-4662-4eb8-b81a-eb2d9f7ef734)

_Originally posted by @temospena in https://github.com/U-Shift/SiteSelection/issues/6#issuecomment-1964611123_

**Comment by temospena** [comment]
Use flowers of proximity concept (applied to 15-min city) as categories of POI

![image](https://github.com/U-Shift/SiteSelection/assets/39107166/b4931e97-c148-434f-b971-b2868504616f)
(Benjamin Buttner - https://www.eiturbanmobility.eu/wp-content/uploads/2022/11/EIT-UrbanMobilityNext9_15-min-City_144dpi.pdf)

**Comment by temospena** [comment]
Still regarding the 15min city concept, these places are for those who LIVE in the city.
It excludes tourism-related POI, such as hotels.
Should we include those?
@valenca13

**Comment by temospena** [comment]
The `public transportation stops` should be used **also** in land use or **exclusively** as a separated input (for the very complex sites)? 🤔

**Comment by temospena** [comment]
@valenca13 [here is a table](https://github.com/U-Shift/SiteSelection/releases/download/0.1/osm_poi_tags.txt) of the amount of POIs extracted from OSM, with their type, to classify according to the literature in X groups.
I would discard all the portuguese names, that are not part of the [OSM tags convention](https://wiki.openstreetmap.org/wiki/Map_features).

**Comment by valenca13** [comment]
@temospena Vamos então usar as 6 grandes categorias mais os edifícios exclusivamente residenciais.

**Comment by temospena** [comment]
```r
summary(landuse_grid$entropy)
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
 0.0000  0.0000  0.0000  0.1229  0.2188  0.8271    1750 
```

So, the max value for almada is 0.82. There are several 0, with only residential.
@valenca13 do we need to normalize then the values before filtering the ones >0.5, or is ready to filter?

**Comment by valenca13** [comment]
@temospena we do not need to normalize the values, since it is already from 0 to 1. Not having a 1 value makes sense in terms of practice. You will never have the same number of different types of land use in a certain area. So the values are very low due to the number of categories. Let's try out like this. If it does not work, we aggregate the categories.

**Comment by valenca13** [comment]
@temospena N is always equal to 7, because we want to evaluate how many possible categories there are in a cell. If only 4 categories are present, then the indicator should take into consideration that there are 3 missing. Depending on the values, it may be coherent to aggregate the categories into the flower of proximity concept. Let's think a little bit.
